### ISSUE TITLE
ModuleNotFoundError: No module named 'segmentator'

### ISSUE THREAD

**Issue by prograguo** [Karbo123/segmentator#1]
I follow the instructions below
```
cd csrc && mkdir build && cd build

cmake .. \
-DCMAKE_PREFIX_PATH=`python -c 'import torch;print(torch.utils.cmake_prefix_path)'` \
-DPYTHON_INCLUDE_DIR=$(python -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())")  \
-DPYTHON_LIBRARY=$(python -c "import distutils.sysconfig as sysconfig; print(sysconfig.get_config_var('LIBDIR'))") \
-DCMAKE_INSTALL_PREFIX=`python -c 'from distutils.sysconfig import get_python_lib; print(get_python_lib())'` 

make && make install # after install, please do not delete this folder (as we only create a symbolic link)
```
but I can not import segmentator
`
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from segmentator import segment_mesh, segment_point, compute_vn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'segmentator'
>>> 

Can you help me？
Thanks！
`

**Comment by Karbo123** [comment]
if you have built the package but cannot find it, maybe you should copy those built files to the python package folder (usually is `python -c 'from distutils.sysconfig import get_python_lib; print(get_python_lib())'`, however, maybe your path is different and you should specify a correct one by yourself); or you can follow other instruction like this one: https://www.scivision.dev/cmake-install-python-package/

**Comment by prograguo** [comment]
ThANK YOU

**Comment by yycdx** [comment]
In my case, python package folder is /opt/conda/envs/spformer/lib/python3.8/site-packages/ (from` python -c 'from distutils.sysconfig import get_python_lib; print(get_python_lib())`). 
Then
`mkdir /opt/conda/envs/spformer/lib/python3.8/site-packages/segmentator`
`cp -rf * /opt/conda/envs/spformer/lib/python3.8/site-packages/segmentator`
`__init__.py` should be copied to python package folder for import package.
Then `import segmentator` works fine.

**Comment by Wang-pengfei** [comment]
I met this error following your instructions. Do you know how to solve this problem?

CMake Warning at /home/pengfei_wang/anaconda3/envs/spformer/lib/python3.8/site-packages/torch/share/cmake/Caffe2/public/protobuf.cmake:88 (message):
  Protobuf cannot be found.  Depending on whether you are building Caffe2 or
  a Caffe2 dependent library, the next warning / error will give you more
  info.
Call Stack (most recent call first):
  /home/pengfei_wang/anaconda3/envs/spformer/lib/python3.8/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:56 (include)
  /home/pengfei_wang/anaconda3/envs/spformer/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  CMakeLists.txt:8 (find_package)


CMake Error at /home/pengfei_wang/anaconda3/envs/spformer/lib/python3.8/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:58 (message):
  Your installed Caffe2 version uses protobuf but the protobuf library cannot
  be found.  Did you accidentally remove it, or have you set the right
  CMAKE_PREFIX_PATH? If you do not have protobuf, you will need to install
  protobuf and set the library path accordingly.
Call Stack (most recent call first):
  /home/pengfei_wang/anaconda3/envs/spformer/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  CMakeLists.txt:8 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/pengfei_wang/3D/segmentator/csrc/build/CMakeFiles/CMakeOutput.log".
See also "/home/pengfei_wang/3D/segmentator/csrc/build/CMakeFiles/CMakeError.log".

**Comment by ryosuke-yamada** [comment]
@Wang-pengfei @Karbo123  
Hi, Did you resolve the error? 
I am also having trouble building with the same error. Can you give me some information?

**Comment by Karbo123** [comment]
@ryosuke-yamada @Wang-pengfei Please read the error info carefully, it says: "Your installed Caffe2 version uses protobuf but the protobuf library cannot be found. Did you accidentally remove it, or have you set the right CMAKE_PREFIX_PATH? If you do not have protobuf, you will need to install protobuf and set the library path accordingly."

But I think in most cases, **you may downgrade the pytorch version to, for example, < 2.0**, because it was caused by pytorch.

**Comment by ryosuke-yamada** [comment]
@Karbo123 Thank you so much reply!
Yes, I was able to solve the error. In my case, the cause of the error was that the CUDA and CuDNN paths were not set correctly.

**Comment by Wang-hui-001** [comment]
I have generated the libsegmentator.so file, but I am unable to import it, and I encounter this error:
Traceback (most recent call last):
  File "/home/wanghui/Downloads/unidet3d-master/segmentator/main.py", line 5, in <module>
    from .csrc.build.libsegmentator import segment_mesh as segment_mesh_fn, segment_point as segment_point_fn
ImportError: attempted relative import with no known parent package
 Do you know how to solve this problem?

**Comment by Karbo123** [comment]
@Wang-hui-001 maybe you can google it before asking question [see here](https://stackoverflow.com/questions/16981921/relative-imports-in-python-3)
