### ISSUE TITLE
关于参数设定以及如何是否有更好的方法？

### ISSUE THREAD

**Issue by Wind010321** [Karbo123/segmentator#10]
作者你好，
  我最近在研究超点生成，请问你的方法的超参设定可以通过哪些方式直接查找到？
  另外，请问关于超点生成部分，你有一些新的方法的推荐吗？
  谢谢你！

**Comment by Karbo123** [comment]
我不太理解什么叫“查找到”？超参数不是需要按需调整吗？

如果您值得是API需要传入什么参数，您可以看一下代码里面的注释部分[code](https://github.com/Karbo123/segmentator/blob/master/main.py)，抱歉API这方面暂时没有写文档详细介绍。

您指的是基于learning的方法，还是基于无监督的非学习方法呢？

如果是基于无监督的非学习方法，其实很多第三方库都有较好的实现，著名的有[scipy](https://docs.scipy.org/doc/scipy/reference/cluster.html)。

如果是基于learning的，抱歉我最近没怎么关注这方面的进展。

**Comment by Wind010321** [comment]
请问说的参数，是只有这两个吗？‘kThresh=0.01, segMinVerts=20)’

**Comment by Karbo123** [comment]
是的
