### ISSUE TITLE
Can I directly use the original segmentator? rather than this one pytorch-plus version?

### ISSUE THREAD

**Issue by Starboy-at-earth** [Karbo123/segmentator#12]
Awkwardly, I have failed to compile the provided beefed-up segmentator.

**Comment by Starboy-at-earth** [comment]
-- The C compiler identification is unknown
-- The CXX compiler identification is GNU 9.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - broken
CMake Error at /usr/share/cmake-3.22/Modules/CMakeTestCCompiler.cmake:69 (message):
  The C compiler

    "/usr/bin/cc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/xxx/1st/3D-STMN-main/segmentator/csrc/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_1ffbe/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_1ffbe.dir/build.make CMakeFiles/cmTC_1ffbe.dir/build
    gmake[1]: Entering directory '/home/xxx/1st/3D-STMN-main/segmentator/csrc/build/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_1ffbe.dir/testCCompiler.c.o
    /usr/bin/cc    -o CMakeFiles/cmTC_1ffbe.dir/testCCompiler.c.o -c /home/xxx    /home/xxx/1st/3D-STMN-main/segmentator/csrc/build/CMakeFiles/CMakeTmp/testCCompiler.c:2:3: error: #error "The CMAKE_C_COMPILER is set to a C++ compiler"
        2 | # error "The CMAKE_C_COMPILER is set to a C++ compiler"
          |   ^~~~~
    gmake[1]: *** [CMakeFiles/cmTC_1ffbe.dir/build.make:78: CMakeFiles/cmTC_1ffbe.dir/testCCompiler.c.o] Error 1
    gmake[1]: Leaving directory '/home/xxx/1st/3D-STMN-main/segmentator/csrc/build/CMakeFiles/CMakeTmp'
    gmake: *** [Makefile:127: cmTC_1ffbe/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:7 (project)


-- Configuring incomplete, errors occurred!
See also "/home/xxx/1st/3D-STMN-main/segmentator/csrc/build/CMakeFiles/CMakeOutput.log".
See also "/home/xxx/1st/3D-STMN-main/segmentator/csrc/build/CMakeFiles/CMakeError.log".
make: *** No targets specified and no makefile found.  Stop.
(3d-stmn) (base) xxx@xxx-a100:~/1st/3D-STMN-main/segmentator$ sh install.sh 
mkdir: cannot create directory ‘build’: File exists
CMake Error: The source directory "/home/xxx/1st/3D-STMN-main/segmentator" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
make: *** No targets specified and no makefile found.  Stop.

**Comment by Karbo123** [comment]
@Starboy-at-earth What's the original segmentator? In addition, your problem appears to be due to an incorrect setup in the compilation environment, which has nothing to do with our code. Maybe you have already solved the problem.

**Comment by Starboy-at-earth** [comment]
@Karbo123  Thank you for your timely reponse!!! I have solved the problem by reinstalling the system.
