### ISSUE TITLE
Problems while trying to make

### ISSUE THREAD

**Issue by K25801** [Karbo123/segmentator#3]
Hi, I encountered a problem related to compilation issues, when I was trying `make`, I got an error:

> SPFormer/segmentator/csrc/segmentator.cpp:389:16: error: expected constructor, destructor, or type conversion before ‘(’ token
 PYBIND11_MODULE(TORCH_EXTENSION_NAME, m)

`CMakeFiles/libsegmentator.dir/build.make:75: recipe for target 'CMakeFiles/libsegmentator.dir/segmentator.cpp.o' failed
make[2]: *** [CMakeFiles/libsegmentator.dir/segmentator.cpp.o] Error 1
CMakeFiles/Makefile2:82: recipe for target 'CMakeFiles/libsegmentator.dir/all' failed
make[1]: *** [CMakeFiles/libsegmentator.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2`

Seems to be issues with pybind11, but I already got the pybind11 successfully installed and tried solutions that can be found on google, it's still not working right now.

**Comment by Karbo123** [comment]
Which version of the C++ compiler are you using? Perhaps your C++ compiler is outdated?

**Comment by K25801** [comment]
Thanks for your reply, my gcc version and cpp version is 7.5.0

`gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) `
`cpp (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.`

Is it too old for your code?

**Comment by Karbo123** [comment]
@K25801 I am not sure. I think it is relevant to either your c++ compiler or the pybind11 package you used.

Please check your installed pybind11 package, and ensure that the c++ compiler can really find where your pybind11 is located.
I think pytorch naturally comes with the installation of pybind11, so maybe you don't need to install pybind11 separately?

If you still cannot build the code, maybe you can manually type the command for compilation, e.g. something like `g++ segmentator.cpp ... ` (followed by options specified by [the cmake script](https://github.com/Karbo123/segmentator/blob/master/csrc/CMakeLists.txt)), and you need to fully understand the cmake script.

**Comment by linxiaoyiyi** [comment]
> Thanks for your reply, my gcc version and cpp version is 7.5.0
> 
> `gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) ` `cpp (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0 Copyright (C) 2017 Free Software Foundation, Inc.`
> 
> Is it too old for your code?

I use the same version, so what version may be useful?
