### ISSUE TITLE
  Command-line error: invalid option: --orig_src_path_name

### ISSUE THREAD

**Issue by AaronNZH** [Karbo123/segmentator#5]
The following error occurred during make. Can you help me fix it?

Make Error at /usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:780 (message):
  Compiling the CUDA compiler identification source file
  "CMakeCUDACompilerId.cu" failed.

  Compiler: /usr/bin/nvcc

  Build flags:

  Id flags: --keep;--keep-dir;tmp -v

  The output was:

  4

  #$ _NVVM_BRANCH_=nvvm

  #$ _SPACE_=

  #$ _CUDART_=cudart

  #$ _HERE_=/usr/lib/nvidia-cuda-toolkit/bin

  #$ _THERE_=/usr/lib/nvidia-cuda-toolkit/bin

  #$ _TARGET_SIZE_=

  #$ _TARGET_DIR_=

  #$ _TARGET_SIZE_=64

  #$ NVVMIR_LIBRARY_DIR=/usr/lib/nvidia-cuda-toolkit/libdevice

  #$
  PATH=/usr/lib/nvidia-cuda-toolkit/bin:/usr/local/cuda-11.4/bin:/home/ubuntu/anaconda3/envs/lavis/bin:/home/ubuntu/anaconda3/condabin:/home/ubuntu/.vscode-server/bin/863d2581ecda6849923a2118d93a088b0745d9d6/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

  #$ LIBRARIES= -L/usr/lib/x86_64-linux-gnu/stubs -L/usr/lib/x86_64-linux-gnu

  #$ rm tmp/a_dlink.reg.c

  #$ gcc -D__CUDA_ARCH_LIST__=520 -E -x c++ -D__CUDACC__ -D__NVCC__
  -D__CUDACC_VER_MAJOR__=12 -D__CUDACC_VER_MINOR__=2
  -D__CUDACC_VER_BUILD__=140 -D__CUDA_API_VER_MAJOR__=12
  -D__CUDA_API_VER_MINOR__=2 -D__NVCC_DIAG_PRAGMA_SUPPORT__=1 -include
  "cuda_runtime.h" -m64 "CMakeCUDACompilerId.cu" -o
  "tmp/CMakeCUDACompilerId.cpp4.ii"

  #$ cudafe++ --c++14 --gnu_version=70500 --display_error_number
  --orig_src_file_name "CMakeCUDACompilerId.cu" --orig_src_path_name
  "/data/NZH/oneformer3d/segmentator/csrc/build/CMakeFiles/3.28.3/CompilerIdCUDA/CMakeCUDACompilerId.cu"
  --allow_managed --m64 --parse_templates --gen_c_file_name
  "tmp/CMakeCUDACompilerId.cudafe1.cpp" --stub_file_name
  "CMakeCUDACompilerId.cudafe1.stub.c" --gen_module_id_file
  --module_id_file_name "tmp/CMakeCUDACompilerId.module_id"
  "tmp/CMakeCUDACompilerId.cpp4.ii"

  Command-line error: invalid option: --orig_src_path_name

  1 catastrophic error detected in this compilation.

  Compilation terminated.

  # --error 0x4 --

Call Stack (most recent call first):
  /usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:8 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:53 (__determine_compiler_id_test)
  /usr/share/cmake-3.28/Modules/CMakeDetermineCUDACompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID)
  /home/ubuntu/anaconda3/lib/python3.8/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:47 (enable_language)
  /home/ubuntu/anaconda3/lib/python3.8/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
  /home/ubuntu/anaconda3/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  CMakeLists.txt:8 (find_package)

**Comment by Karbo123** [comment]
Why do you use nvcc to compile the code? besides, I think it's unrelated to our code, the message said: Compiling the CUDA compiler identification source file
"CMakeCUDACompilerId.cu" failed.
This is because cmake was trying to determine a proper compiler but it failed.

**Comment by AaronNZH** [comment]
I have no idea why it was compiled by nvcc, I just executed the make command as README.

**Comment by Karbo123** [comment]
https://cmake.org/cmake/help/latest/command/enable_language.html

https://stackoverflow.com/questions/45933732/how-to-specify-a-compiler-in-cmake

please specify the c++ language, and maybe specify the compiler path to cmake as well.

**Comment by Karbo123** [comment]
close the issue for now since it is unrelated to our code

**Comment by balanceNB** [comment]
I had the exact same problem, which was not fixed after specifying the CMake compiler
