### ISSUE TITLE
Your installed Caffe2 version uses cuDNN but I cannot find the cuDNN libraries.

### ISSUE THREAD

**Issue by hxiaoj** [Karbo123/segmentator#7]
Hello!
When I try to build it, i encounter the following:
CMake Error at /anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:96 (message):
  Your installed Caffe2 version uses cuDNN but I cannot find the cuDNN
  libraries.  Please set the proper cuDNN prefixes and / or install cuDNN.
Call Stack (most recent call first):
  /anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  CMakeLists.txt:8 (find_package)

And I have installed the cudnn by: 
conda install cudnn

How can I solve it?

**Comment by Karbo123** [comment]
I only tested with pytorch installed via pip, maybe you can give it a try.

Besides, you may find this helpful: [Easier installation with setuptools](https://github.com/Karbo123/segmentator/pull/6)

By the way, our library does not depend on cuDNN.

**Comment by xiac20** [comment]
I met the same problem, but failed to fix it. Passing the addition configuration seems doesn't work well.
