### ISSUE TITLE
分隔scannetv2训练集出现问题

### ISSUE THREAD

**Issue by rabbit-11** [Karbo123/segmentator#8]
如图
![image](https://github.com/Karbo123/segmentator/assets/54898118/cfc8afcb-ecfd-41e7-b0b4-55736d46e93a)
vertices和faces应该都读到了，但是运行segment_mesh函数的时候出错了，请问一下这是什么问题导致的

**Comment by Karbo123** [comment]
你可以试下[最简单的例子](https://github.com/Karbo123/segmentator?tab=readme-ov-file#examples)是否仍会导致错误

你的pytorch具体版本是什么？可以通过此查看
```
import torch
print(torch.__version__)
```

**Comment by rabbit-11** [comment]
python== 3.8 pytorch==1.12.1 torchvision==0.13.1 cudatoolkit=11.3
有测试用的点云数据吗，或者如果说是readme里的example的话，已经试过了也会报错

**Comment by Karbo123** [comment]
可以尝试降低pytorch版本看能不能解决？比如pytorch1.8

**Comment by Karbo123** [comment]
close for now
