### ISSUE TITLE
Some questions about the code parameters.

### ISSUE THREAD

**Issue by Wind010321** [Karbo123/segmentator#9]
Hello, I have strong interest in your method based on super-point graph(SPG). There is an excellent work based on SPG called [SPT](https://github.com/drprojects/superpoint_transformer). Can you give some update to your excellent work to have more stars?

**Comment by Karbo123** [comment]
What updates should I make? I can't get your point.

**Comment by Wind010321** [comment]
这里有一个SPG的更新版本，他的名字叫SPT。新方法是利用了U-Net网络的思想，对第一次partition获得的L1 superpoint，再进行partition，获得语义较强的L2 superpoint。在此基础上(L2 superpoint 提供high-level特征)与原先的L1 superpoint（提供low-level信息）联合进行下游的任务。 
不好意思，我刚刚看到你的回复。

**Comment by Wind010321** [comment]
你好，我对以下的超点获取代码的参数理解，存在一些疑问：
[https://github.com/Karbo123/segmentator/blob/master/main.py](url)
请问该文件中的segment_mesh函数的参数：
1. kThresh： 如果将对应数值增大，最后产生的超点区域可能会增大吗？
2. segMinVerts： 如果我想获得较大的超点，仅修改本参数的数值，就可达到对应的效果吧？
期待您的回复！

**Comment by Karbo123** [comment]
@Wind010321 

[代码注释](https://github.com/Karbo123/segmentator/blob/master/main.py#L6-L15)里面应该写得很清楚了。
- 是的。`kThresh` 是一个阈值参数，增大它会导致同一个聚类类别里面的点的数量变多；
- 是的。`segMinVerts` 可以控制一个聚类类别里面的点的最小数量。

建议你自行编译代码试一下效果就清楚了。你可以两个都调整，看看哪一个调节得更为方便。

**Comment by Wind010321** [comment]
感谢你！
